import os
import subprocess
from pathlib import Path

# -------- CONFIGURATION --------
# The directory where our previous script saved the secretome files
input_dir = Path("/mnt/e/Fusarium_fujikuroi_analysis/cds_data/protein_input/effectorp_input")

# Path to the EffectorP 3.0 script
effectorp_script = "/mnt/e/Fusarium_fujikuroi_analysis/scripts/EffectorP-3.0/EffectorP.py"

# Where to save results
output_dir = Path("/mnt/e/Fusarium_fujikuroi_analysis/cds_data/protein_input/effectorp_results")
output_dir.mkdir(parents=True, exist_ok=True)

# Final summary list path
effector_gene_list_path = output_dir / "all_unique_effector_ids.txt"

ISOLATES = ["5B", "5C", "B20", "C1995", "CFF1", "CFF2", "E282", "FSU48", 
            "IMI58289", "KSU3368", "M567", "MRC2276", "NCIM1100"]

all_effector_ids = set()

# -------- SCAN AND RUN --------
print(f"{'Isolate':<12} | {'Status':<15} | {'Predicted Effectors'}")
print("-" * 50)

for isolate in ISOLATES:
    # Match the file name generated by our previous "Three Crown" script
    faa_file = input_dir / f"{isolate}.secretome.faa"

    if not faa_file.exists():
        print(f"{isolate:<12} |  Missing File")
        continue

    output_path = output_dir / f"{isolate}_effectorp_results.txt"
    
    # Run EffectorP 3.0
    # Note: Using subprocess.run. We capture output to avoid cluttering the terminal.
    try:
        subprocess.run(
            ["python", effectorp_script, "-i", str(faa_file), "-o", str(output_path)],
            check=True,
            capture_output=True,
            text=True
        )
    except subprocess.CalledProcessError as e:
        print(f"{isolate:<12} |  Error: {e.stderr[:50]}...")
        continue

    # -------- PARSE EFFECTORP 3.0 OUTPUT --------
    # EffectorP 3.0 columns usually are: Identifier, Prediction, Probability, etc.
    isolate_count = 0
    if output_path.exists():
        with open(output_path, 'r') as f:
            for line in f:
                # Skip headers and empty lines
                if line.startswith("#") or not line.strip() or "Identifier" in line:
                    continue
                
                parts = line.strip().split("\t")
                if len(parts) < 2:
                    continue
                
                gene_id = parts[0]
                prediction = parts[1] # e.g., "Effector (Apoplastic)"
                
                if "Effector" in prediction:
                    all_effector_ids.add(gene_id)
                    isolate_count += 1
        
        print(f"{isolate:<12} | Completed     | {isolate_count}")
    else:
        print(f"{isolate:<12} |  No output file")

# -------- WRITE FINAL SUMMARY LIST --------
with open(effector_gene_list_path, "w") as f:
    for eid in sorted(all_effector_ids):
        f.write(f"{eid}\n")

print("-" * 50)
print(f"Total unique effector IDs across all isolates: {len(all_effector_ids)}")
print(f"Master list written to: {effector_gene_list_path}")

